[Enhancement] Backend refactor
Zaptyp/wulkanowy-web pull request #9
Opened 2022-05-31 14:03 UTC by Marioneq4958

2022-05-31 19:33 UTC, Zaptyp requested changes
Nice!

2022-05-31 19:33 UTC, Zaptyp commented on backend/tests/endpoints/login.py
> -        assert login.json()["host"] == "fakelog.tk"
Why this code be deleted?

2022-05-31 19:33 UTC, Zaptyp commented on backend/tests/endpoints/login.py
> -        assert login.json()["host"] == "fakelog.tk"
Revert this change

2022-05-31 19:40 UTC, Marioneq4958 commented on backend/tests/endpoints/login.py
> -        assert login.json()["host"] == "fakelog.tk"
Because now there isn't `host` in `login.json()`

2022-06-01 15:15 UTC, Zaptyp approved these changes

2022-06-01 15:15 UTC, merged